version: "3.5"

services:
  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: activerecord_import_test

  postgresql:
    image: postgis/postgis:10-2.5
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: activerecord_import_test

  app:
    build:
      context: .
    environment:
      DB_HOST: mysql
      AR_VERSION: 7.0
    volumes:
      - .:/usr/src/app
    depends_on:
      - mysql
      - postgresql
    command: tail -f /dev/null

volumes:
  mysql-data:
  postgresql-data:
